---
- name: cisco_sh_ver
  hosts: gns3-group
  gather_facts: no
  
  tasks:




  - name: configure top level configuration
    cisco.ios.ios_config:
      lines: hostname {{ inventory_hostname }}

  - name: configure interface settings
    cisco.ios.ios_config:
      lines:
      - description test interface
      - ip address 172.31.1.1 255.255.255.0
      parents: interface GigabitEthernet1/1

  - name: configure ip helpers on multiple interfaces
    cisco.ios.ios_config:
      lines:
      - ip helper-address 172.26.1.10
      - ip helper-address 172.26.3.8
      parents: '{{ item }}'
    with_items:
    - interface GigabitEthernet1/2
    - interface GigabitEthernet1/3
    - interface GigabitEthernet1/0

  - name: configure policer in Scavenger class
    cisco.ios.ios_config:
      lines:
      - conform-action transmit
      - exceed-action drop
      parents:
      - policy-map Foo
      - class Scavenger
      - police cir 64000

  - name: load new acl into device
    cisco.ios.ios_config:
      lines:
      - 10 permit ip host 192.0.2.1 any log
      - 20 permit ip host 192.0.2.2 any log
      - 30 permit ip host 192.0.2.3 any log
      - 40 permit ip host 192.0.2.4 any log
      - 50 permit ip host 192.0.2.5 any log
      parents: ip access-list extended test
      before: no ip access-list extended test
      match: exact

  - name: check the running-config against master config
    cisco.ios.ios_config:
      diff_against: intended
      intended_config: "{{ lookup('file', 'master.cfg') }}"

  - name: check the startup-config against the running-config
    cisco.ios.ios_config:
      diff_against: startup
      diff_ignore_lines:
      - ntp clock .*

  - name: save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified

  - name: for idempotency, use full-form commands
    cisco.ios.ios_config:
      lines:
        # - shut
      - shutdown
      # parents: int gig1/0/11
      parents: interface GigabitEthernet0/3

  # Set boot image based on comparison to a group_var (version) and the version
  # that is returned from the `ios_facts` module
  - name: SETTING BOOT IMAGE
    cisco.ios.ios_config:
      lines:
      - no boot system
      - boot system flash bootflash:{{new_image}}
      host: '{{ inventory_hostname }}'
    when: ansible_net_version != version
  - name: render a Jinja2 template onto an IOS device
    cisco.ios.ios_config:
      backup: yes
      src: ios_template.j2

  - name: configurable backup path
    cisco.ios.ios_config:
      src: ios_template.j2
      backup: yes
      backup_options:
        filename: backup.cfg
        dir_path: /home/user
