---
- name: cisco_gather
  hosts: gns3-group
  gather_facts: no
  

    
  tasks:
  - name: configurable backup path
    cisco.ios.ios_config:
      src: ios_template.j2
      backup: yes
      backup_options:
        filename: backup.cfg
        dir_path: /home/slimo
