---
- name: cisco_sh_ver
  hosts: all
  gather_facts: no
  
  tasks:
  
  - name: Configure the login banner
    cisco.ios.ios_banner:
      banner: login
      text: |
        this is my login banner
        that contains a multiline
        string
      state: present
      
  - name: configure top level configuration
    cisco.ios.ios_config:
      lines: hostname {{ inventory_hostname }}
