---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: ios
  gather_facts: no
  
 - tasks: 
   - name: Get running config
     ios_command:
       commands: show run
     register: show_run

   - name: Save config to file
     copy:
       content: "{{ show_run.stdout[0] }}"
       dest: "/home/slimo/backups/{{inventory_hostname}}-{{ansible_facts.date_time.}}plachta.txt"
