
---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:
     - name: configurable backup path
       ios_config:
   #      src: ios_template.j2
         backup: yes
         backup_options:
           filename: backup.cfg
           dir_path: /home/slimo

