
---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
       backup_path: /home/slimo/backups/
      register: config_output
      
