---
- name: asdf
  hosts: ios
  gather_facts: yes
  
  tasks:

    - name: Merge provided configuration with device configuration
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv4:
            - address: 192.168.0.1/24
        state: replaced
