---
- name: asdf
  hosts: ios
  connection: ansible.netcommon.network_cli
  gather_facts: no
  
  tasks:
   - name: configure hostname
     cisco.ios.ios_config:
       lines: hostname {{ inventory_hostname }}
