---
- hosts: gns3-group
  gather_facts: no

  vars:
    vlan: 18

  tasks:
     - name: Create vlan
       ios_vlan:
         vlan_id: "{{ vlan }}"
         name: test-vlan1
         state: present

     - name: Add interfaces to VLAN
       ios_vlan:
         vlan_id: "{{ vlan }}"
         interfaces:
           - GigabitEthernet1/3
