  
---
- hosts: all
  gather_facts: no
#  connection: local
  

  
  - name: Check System Device
   ios_command:
      commands: show version
    register: system
    
  - debug: msg="{{ system.stdout}}"
