---

- name: Network Getting Started First Playbook
  #connection: network_cli
 
  gather_facts: true
  hosts: all
  tasks:

    - name: Merge provided configuration with device configuration
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv4:
            - address: 192.168.0.1/24
              secondary: True
          - name: GigabitEthernet0/2
            ipv4:
            - address: 192.168.0.2/24
          - name: GigabitEthernet0/3
            ipv6:
            - address: fd5d:12c9:2201:1::1/64
          - name: GigabitEthernet0/3.100
            ipv4:
            - address: 192.168.0.3/24
        state: merged


